# Generated by Django 3.0.3 on 2020-03-14 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('question', models.TextField(max_length=500, verbose_name='Frage')),
                ('description', models.TextField(blank=True, default='', max_length=1000, verbose_name='Beschreibung')),
                ('open_date', models.DateTimeField(verbose_name='Startdatum')),
                ('close_date', models.DateTimeField(verbose_name='Enddatum')),
                ('display_order', models.IntegerField(default=0, verbose_name='Anzeigereihenfolge')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('add_menu_link', models.BooleanField(default=True, verbose_name='Link zum Menü hinzufügen')),
            ],
            options={
                'permissions': (('can_see_poll_results', 'Kann Abstimmungsergebnisse sehen'),),
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.PositiveSmallIntegerField(choices=[(1, 'Ja'), (0, 'Nein'), (2, 'Enthaltung')])),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Letztes Update')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juntagrico_polling.Poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'poll'), name='unique user vote'),
        ),
    ]
